version: "3.4"

x-default-healthcheck: &default-healthcheck
  test: curl --fail http://localhost:80 || exit 1
  interval: 60s
  timeout: 10s
  retries: 5
  start_period: 60s

x-default-restart-policy: &default-restart-policy
  condition: any
  delay: 30s
  window: 120s

x-default-update-config: &default-update-config
  parallelism: 1
  delay: 30s
  failure_action: rollback

services:
  rabbitmq:
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: '0.25'
          memory: 300M
      restart_policy:
        <<: *default-restart-policy
      update_config:
        <<: *default-update-config
    healthcheck:
      <<: *default-healthcheck
      test: rabbitmq-diagnostics -q ping || exit 1
    image: rabbitmq:3-management
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=password
  redis:
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: '0.10'
          memory: 50M
      restart_policy:
        <<: *default-restart-policy
      update_config:
        <<: *default-update-config
    healthcheck:
      <<: *default-healthcheck
      test: redis-cli ping || exit 1
    image: redis:7
  account-observer:
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: '0.10'
          memory: 150M
      restart_policy:
        <<: *default-restart-policy
      update_config:
        <<: *default-update-config
    healthcheck:
      <<: *default-healthcheck
      test: curl --fail http://localhost:8080 || exit 1
    image: jesuswebdev/binance-trader-account-observer:4aa749e099323516aeb80568c97a3593c8b8a8fe
    environment:
      - NODE_ENV=production
    secrets:
      - source: account-observer-env-v1
        target: /usr/app/account-observer/.env.production
        uid: '1000'
        gid: '1000'
        mode: 0700
  markets-observer:
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: '0.10'
          memory: 100M
      restart_policy:
        <<: *default-restart-policy
      update_config:
        <<: *default-update-config
    healthcheck:
      <<: *default-healthcheck
      test: curl --fail http://localhost:8080 || exit 1
    image: jesuswebdev/binance-trader-markets-observer:4aa749e099323516aeb80568c97a3593c8b8a8fe
    environment:
      - NODE_ENV=production
    secrets:
      - source: markets-observer-env-v1
        target: /usr/app/markets-observer/.env.production
        uid: '1000'
        gid: '1000'
        mode: 0700
    depends_on:
      - candles-processor
      - rabbitmq
  candles-processor:
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: '0.50'
          memory: 500M
      restart_policy:
        <<: *default-restart-policy
      update_config:
        <<: *default-update-config
    healthcheck:
      <<: *default-healthcheck
      test: curl --fail http://localhost:8080 || exit 1
    image: jesuswebdev/binance-trader-candles-processor:4aa749e099323516aeb80568c97a3593c8b8a8fe
    environment:
      - NODE_ENV=production
    secrets:
      - source: candles-processor-env-v1
        target: /usr/app/candles-processor/.env.production
        uid: '1000'
        gid: '1000'
        mode: 0700
    depends_on:
      - signals-processor
      - positions-processor
      - rabbitmq
      - redis
  signals-processor:
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: '0.15'
          memory: 150M
      restart_policy:
        <<: *default-restart-policy
      update_config:
        <<: *default-update-config
    healthcheck:
      <<: *default-healthcheck
      test: curl --fail http://localhost:8080 || exit 1
    image: jesuswebdev/binance-trader-signals-processor:4aa749e099323516aeb80568c97a3593c8b8a8fe
    environment:
      - NODE_ENV=production
    secrets:
      - source: signals-processor-env-v1
        target: /usr/app/signals-processor/.env.production
        uid: '1000'
        gid: '1000'
        mode: 0700
    depends_on:
      - positions-processor
      - rabbitmq
      - redis
  positions-processor:
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: '0.15'
          memory: 150M
      restart_policy:
        <<: *default-restart-policy
      update_config:
        <<: *default-update-config
    healthcheck:
      <<: *default-healthcheck
      test: curl --fail http://localhost:8080 || exit 1
    image: jesuswebdev/binance-trader-positions-processor:4aa749e099323516aeb80568c97a3593c8b8a8fe
    environment:
      - NODE_ENV=production
    secrets:
      - source: positions-processor-env-v4
        target: /usr/app/positions-processor/.env.production
        uid: '1000'
        gid: '1000'
        mode: 0700
    depends_on:
      - trader
      - rabbitmq
  trader:
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: '0.15'
          memory: 150M
      restart_policy:
        <<: *default-restart-policy
      update_config:
        <<: *default-update-config
    healthcheck:
      <<: *default-healthcheck
      test: curl --fail http://localhost:8080 || exit 1
    image: jesuswebdev/binance-trader-trader:4aa749e099323516aeb80568c97a3593c8b8a8fe
    environment:
      - NODE_ENV=production
    secrets:
      - source: trader-env-v3
        target: /usr/app/trader/.env.production
        uid: '1000'
        gid: '1000'
        mode: 0700
    depends_on:
      - account-observer
      - rabbitmq
  cancel-unfilled-orders-service:
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: '0.1'
          memory: 125M
      restart_policy:
        <<: *default-restart-policy
      update_config:
        <<: *default-update-config
    healthcheck:
      <<: *default-healthcheck
      test: curl --fail http://localhost:3000 || exit 1
    image: jesuswebdev/binance-trader-cancel-unfilled-orders-service:4aa749e099323516aeb80568c97a3593c8b8a8fe
    environment:
      - NODE_ENV=production
    secrets:
      - source: cancel-unfilled-orders-service-env-v1
        target: /usr/app/cancel-unfilled-orders-service/.env.production
        uid: '1000'
        gid: '1000'
        mode: 0700
  update-market-orders-service:
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: '0.1'
          memory: 125M
      restart_policy:
        <<: *default-restart-policy
      update_config:
        <<: *default-update-config
    healthcheck:
      <<: *default-healthcheck
      test: curl --fail http://localhost:3000 || exit 1
    image: jesuswebdev/binance-trader-update-market-orders-service:4aa749e099323516aeb80568c97a3593c8b8a8fe
    environment:
      - NODE_ENV=production
    secrets:
      - source: update-market-orders-service-env-v1
        target: /usr/app/update-market-orders-service/.env.production
        uid: '1000'
        gid: '1000'
        mode: 0700

secrets:
  markets-observer-env-v1:
    external: true
  account-observer-env-v1:
    external: true
  candles-processor-env-v1:
    external: true
  signals-processor-env-v1:
    external: true
  positions-processor-env-v4:
    external: true
  trader-env-v3:
    external: true
  cancel-unfilled-orders-service-env-v1:
    external: true
  update-market-orders-service-env-v1:
    external: true