version: "3.4"

x-default-healthcheck: &default-healthcheck
  test: curl --fail http://localhost:80 || exit 1
  interval: 60s
  timeout: 10s
  retries: 5
  start_period: 60s

x-default-restart-policy: &default-restart-policy
  condition: any
  delay: 30s
  window: 120s

x-default-update-config: &default-update-config
  parallelism: 1
  delay: 30s
  failure_action: rollback

services:
  account-observer:
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: '0.10'
          memory: 150M
      restart_policy:
        <<: *default-restart-policy
      update_config:
        <<: *default-update-config
    healthcheck:
      <<: *default-healthcheck
      test: curl --fail http://localhost:8080 || exit 1
    image: jesuswebdev/binance-trader-account-observer:e40b84199dce6d1e9796ce376faae07188c32571
    environment:
      - NODE_ENV=production
    secrets:
      - source: account-observer-env-v1
        target: /usr/app/account-observer/.env.production
        uid: '1000'
        gid: '1000'
        mode: 0700
  markets-observer:
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: '0.10'
          memory: 100M
      restart_policy:
        <<: *default-restart-policy
      update_config:
        <<: *default-update-config
    healthcheck:
      <<: *default-healthcheck
      test: curl --fail http://localhost:8080 || exit 1
    image: jesuswebdev/binance-trader-markets-observer:18b8132cb96cc21c41d347696d381b26f1f19b2c
    environment:
      - NODE_ENV=production
    secrets:
      - source: markets-observer-env-v1
        target: /usr/app/markets-observer/.env.production
        uid: '1000'
        gid: '1000'
        mode: 0700
    depends_on:
      - candles-processor
    networks:
      - rabbitmq
  candles-processor:
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: '0.50'
          memory: 500M
      restart_policy:
        <<: *default-restart-policy
      update_config:
        <<: *default-update-config
    healthcheck:
      <<: *default-healthcheck
      test: curl --fail http://localhost:8080 || exit 1
    image: jesuswebdev/binance-trader-candles-processor:e40b84199dce6d1e9796ce376faae07188c32571
    environment:
      - NODE_ENV=production
    secrets:
      - source: candles-processor-env-v1
        target: /usr/app/candles-processor/.env.production
        uid: '1000'
        gid: '1000'
        mode: 0700
    depends_on:
      - signals-processor
      - positions-processor
    networks:
      - redis
      - rabbitmq
  signals-processor:
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: '0.15'
          memory: 150M
      restart_policy:
        <<: *default-restart-policy
      update_config:
        <<: *default-update-config
    healthcheck:
      <<: *default-healthcheck
      test: curl --fail http://localhost:8080 || exit 1
    image: jesuswebdev/binance-trader-signals-processor:e40b84199dce6d1e9796ce376faae07188c32571
    environment:
      - NODE_ENV=production
    secrets:
      - source: signals-processor-env-v1
        target: /usr/app/signals-processor/.env.production
        uid: '1000'
        gid: '1000'
        mode: 0700
    depends_on:
      - positions-processor
    networks:
      - redis
      - rabbitmq
  positions-processor:
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: '0.15'
          memory: 150M
      restart_policy:
        <<: *default-restart-policy
      update_config:
        <<: *default-update-config
    healthcheck:
      <<: *default-healthcheck
      test: curl --fail http://localhost:8080 || exit 1
    image: jesuswebdev/binance-trader-positions-processor:cd7b8a479decb30881a565c4a0e1ee4d247c8977
    environment:
      - NODE_ENV=production
    secrets:
      - source: positions-processor-env-v1
        target: /usr/app/positions-processor/.env.production
        uid: '1000'
        gid: '1000'
        mode: 0700
    depends_on:
      - trader
    networks:
      - rabbitmq
  trader:
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: '0.15'
          memory: 150M
      restart_policy:
        <<: *default-restart-policy
      update_config:
        <<: *default-update-config
    healthcheck:
      <<: *default-healthcheck
      test: curl --fail http://localhost:8080 || exit 1
    image: jesuswebdev/binance-trader-trader:75796cd68e5361b91eb7337b8f50c914793ec238
    environment:
      - NODE_ENV=production
    secrets:
      - source: trader-env-v2
        target: /usr/app/trader/.env.production
        uid: '1000'
        gid: '1000'
        mode: 0700
    depends_on:
      - account-observer
    networks:
      - rabbitmq
  update-account-balance-service:
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: '0.1'
          memory: 150M
      restart_policy:
        <<: *default-restart-policy
      update_config:
        <<: *default-update-config
    healthcheck:
      <<: *default-healthcheck
      test: curl --fail http://localhost:3000 || exit 1
    image: jesuswebdev/binance-trader-update-account-balance-service:e2ff9630a0e18644128c42668b82ed03724fd3e4
    environment:
      - NODE_ENV=production
    secrets:
      - source: update-account-balance-service-env-v1
        target: /usr/app/update-account-balance-service/.env.production
        uid: '1000'
        gid: '1000'
        mode: 0700
    networks:
      - redis
      - rabbitmq

networks:
  redis:
    external: true
  rabbitmq:
    external: true

secrets:
  markets-observer-env-v1:
    external: true
  account-observer-env-v1:
    external: true
  candles-processor-env-v1:
    external: true
  signals-processor-env-v1:
    external: true
  positions-processor-env-v1:
    external: true
  trader-env-v2:
    external: true
  update-account-balance-service-env-v1:
    external: true