version: "3.4"

x-default-healthcheck: &default-healthcheck
  test: curl --fail http://localhost:80 || exit 1
  interval: 60s
  timeout: 10s
  retries: 5
  start_period: 60s

x-default-restart-policy: &default-restart-policy
  condition: on-failure
  delay: 30s
  window: 120s

x-default-update-config: &default-update-config
  parallelism: 1
  delay: 30s
  failure_action: rollback

services:
  rabbitmq:
    deploy:
      replicas: 1
      restart_policy:
        <<: *default-restart-policy
      update_config:
        <<: *default-update-config
    healthcheck:
      <<: *default-healthcheck
      test: rabbitmq-diagnostics -q ping || exit 1
    image: rabbitmq:3-management
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=password
  account-observer:
    deploy:
      replicas: 1
      restart_policy:
        <<: *default-restart-policy
      update_config:
        <<: *default-update-config
    healthcheck:
      <<: *default-healthcheck
      test: curl --fail http://localhost:8080 || exit 1
    image: jesuswebdev/binance-trader/account-observer:${API_TAG:-c2fc59526e80b9203fc601b8b0bfe810e6260653}
    environment:
      - NODE_ENV=production
    secrets:
      - source: account-observer-env-v1
        target: /usr/app/account-observer/.env.production
        uid: '1000'
        gid: '1000'
        mode: 0700
  markets-observer:
    deploy:
      replicas: 1
      restart_policy:
        <<: *default-restart-policy
      update_config:
        <<: *default-update-config
    healthcheck:
      <<: *default-healthcheck
      test: curl --fail http://localhost:8080 || exit 1
    image: jesuswebdev/binance-trader/markets-observer:${API_TAG:-c2fc59526e80b9203fc601b8b0bfe810e6260653}
    environment:
      - NODE_ENV=production
    secrets:
      - source: markets-observer-env-v1
        target: /usr/app/markets-observer/.env.production
        uid: '1000'
        gid: '1000'
        mode: 0700
  candles-processor:
    deploy:
      replicas: 1
      restart_policy:
        <<: *default-restart-policy
      update_config:
        <<: *default-update-config
    healthcheck:
      <<: *default-healthcheck
      test: curl --fail http://localhost:8080 || exit 1
    image: jesuswebdev/binance-trader/candles-processor:${API_TAG:-c2fc59526e80b9203fc601b8b0bfe810e6260653}
    environment:
      - NODE_ENV=production
    secrets:
      - source: candles-processor-env-v1
        target: /usr/app/candles-processor/.env.production
        uid: '1000'
        gid: '1000'
        mode: 0700
  signals-processor:
    deploy:
      replicas: 1
      restart_policy:
        <<: *default-restart-policy
      update_config:
        <<: *default-update-config
    healthcheck:
      <<: *default-healthcheck
      test: curl --fail http://localhost:8080 || exit 1
    image: jesuswebdev/binance-trader/signals-processor:${API_TAG:-c2fc59526e80b9203fc601b8b0bfe810e6260653}
    environment:
      - NODE_ENV=production
    secrets:
      - source: signals-processor-env-v1
        target: /usr/app/signals-processor/.env.production
        uid: '1000'
        gid: '1000'
        mode: 0700
  positions-processor:
    deploy:
      replicas: 1
      restart_policy:
        <<: *default-restart-policy
      update_config:
        <<: *default-update-config
    healthcheck:
      <<: *default-healthcheck
      test: curl --fail http://localhost:8080 || exit 1
    image: jesuswebdev/binance-trader/positions-processor:${API_TAG:-c2fc59526e80b9203fc601b8b0bfe810e6260653}
    environment:
      - NODE_ENV=production
    secrets:
      - source: positions-processor-env-v1
        target: /usr/app/positions-processor/.env.production
        uid: '1000'
        gid: '1000'
        mode: 0700

secrets:
  markets-observer-env-v1:
    external: true
  account-observer-env-v1:
    external: true
  candles-processor-env-v1:
    external: true
  signals-processor-env-v1:
    external: true
  positions-processor-env-v1:
    external: true