import { Pair } from '.';

export const ALL_PAIRS: Pair[] = [
  {
    symbol: 'BTCUSDT',
    quoteAsset: 'USDT',
    baseAsset: 'BTC',
    priceTickSize: 0.01,
    stepSize: 0.00001,
  },
  {
    symbol: 'ETHUSDT',
    quoteAsset: 'USDT',
    baseAsset: 'ETH',
    priceTickSize: 0.01,
    stepSize: 0.0001,
  },
  {
    symbol: 'BNBUSDT',
    quoteAsset: 'USDT',
    baseAsset: 'BNB',
    priceTickSize: 0.1,
    stepSize: 0.001,
  },
  {
    symbol: 'LTCUSDT',
    quoteAsset: 'USDT',
    baseAsset: 'LTC',
    priceTickSize: 0.01,
    stepSize: 0.001,
  },
  {
    symbol: 'ADAUSDT',
    quoteAsset: 'USDT',
    baseAsset: 'ADA',
    priceTickSize: 0.0001,
    stepSize: 0.1,
  },
  {
    symbol: 'XRPUSDT',
    quoteAsset: 'USDT',
    baseAsset: 'XRP',
    priceTickSize: 0.0001,
    stepSize: 1,
  },
  {
    symbol: 'EOSUSDT',
    quoteAsset: 'USDT',
    baseAsset: 'EOS',
    priceTickSize: 0.0001,
    stepSize: 0.1,
  },
  {
    symbol: 'XLMUSDT',
    quoteAsset: 'USDT',
    baseAsset: 'XLM',
    priceTickSize: 0.0001,
    stepSize: 1,
  },
  {
    symbol: 'TRXUSDT',
    quoteAsset: 'USDT',
    baseAsset: 'TRX',
    priceTickSize: 0.00001,
    stepSize: 0.1,
  },
  {
    symbol: 'VETUSDT',
    quoteAsset: 'USDT',
    baseAsset: 'VET',
    priceTickSize: 0.00001,
    stepSize: 0.1,
  },
  {
    symbol: 'LINKUSDT',
    quoteAsset: 'USDT',
    baseAsset: 'LINK',
    priceTickSize: 0.001,
    stepSize: 0.01,
  },
  {
    symbol: 'ZILUSDT',
    quoteAsset: 'USDT',
    baseAsset: 'ZIL',
    priceTickSize: 0.00001,
    stepSize: 0.1,
  },
  {
    symbol: 'ZECUSDT',
    quoteAsset: 'USDT',
    baseAsset: 'ZEC',
    priceTickSize: 0.01,
    stepSize: 0.001,
  },
  {
    symbol: 'DASHUSDT',
    quoteAsset: 'USDT',
    baseAsset: 'DASH',
    priceTickSize: 0.01,
    stepSize: 0.001,
  },
  {
    symbol: 'THETAUSDT',
    quoteAsset: 'USDT',
    baseAsset: 'THETA',
    priceTickSize: 0.001,
    stepSize: 0.1,
  },
  {
    symbol: 'ENJUSDT',
    quoteAsset: 'USDT',
    baseAsset: 'ENJ',
    priceTickSize: 0.0001,
    stepSize: 0.1,
  },
  {
    symbol: 'MATICUSDT',
    quoteAsset: 'USDT',
    baseAsset: 'MATIC',
    priceTickSize: 0.0001,
    stepSize: 0.1,
  },
  {
    symbol: 'ATOMUSDT',
    quoteAsset: 'USDT',
    baseAsset: 'ATOM',
    priceTickSize: 0.001,
    stepSize: 0.01,
  },
  {
    symbol: 'FTMUSDT',
    quoteAsset: 'USDT',
    baseAsset: 'FTM',
    priceTickSize: 0.0001,
    stepSize: 1,
  },
  {
    symbol: 'ALGOUSDT',
    quoteAsset: 'USDT',
    baseAsset: 'ALGO',
    priceTickSize: 0.0001,
    stepSize: 1,
  },
  {
    symbol: 'DOGEUSDT',
    quoteAsset: 'USDT',
    baseAsset: 'DOGE',
    priceTickSize: 0.00001,
    stepSize: 1,
  },
  {
    symbol: 'SHIBUSDT',
    quoteAsset: 'USDT',
    baseAsset: 'SHIB',
    priceTickSize: 1e-8,
    stepSize: 1,
  },
  {
    symbol: 'XTZUSDT',
    quoteAsset: 'USDT',
    baseAsset: 'XTZ',
    priceTickSize: 0.001,
    stepSize: 0.1,
  },
  {
    symbol: 'HBARUSDT',
    quoteAsset: 'USDT',
    baseAsset: 'HBAR',
    priceTickSize: 0.0001,
    stepSize: 1,
  },
  {
    symbol: 'STXUSDT',
    quoteAsset: 'USDT',
    baseAsset: 'STX',
    priceTickSize: 0.0001,
    stepSize: 0.1,
  },
  {
    symbol: 'BCHUSDT',
    quoteAsset: 'USDT',
    baseAsset: 'BCH',
    priceTickSize: 0.1,
    stepSize: 0.001,
  },
  {
    symbol: 'SOLUSDT',
    quoteAsset: 'USDT',
    baseAsset: 'SOL',
    priceTickSize: 0.01,
    stepSize: 0.01,
  },
  {
    symbol: 'LRCUSDT',
    quoteAsset: 'USDT',
    baseAsset: 'LRC',
    priceTickSize: 0.0001,
    stepSize: 1,
  },
  {
    symbol: 'MANAUSDT',
    quoteAsset: 'USDT',
    baseAsset: 'MANA',
    priceTickSize: 0.0001,
    stepSize: 1,
  },
  {
    symbol: 'CRVUSDT',
    quoteAsset: 'USDT',
    baseAsset: 'CRV',
    priceTickSize: 0.0001,
    stepSize: 0.1,
  },
  {
    symbol: 'SANDUSDT',
    quoteAsset: 'USDT',
    baseAsset: 'SAND',
    priceTickSize: 0.0001,
    stepSize: 1,
  },
  {
    symbol: 'DOTUSDT',
    quoteAsset: 'USDT',
    baseAsset: 'DOT',
    priceTickSize: 0.001,
    stepSize: 0.01,
  },
  {
    symbol: 'EGLDUSDT',
    quoteAsset: 'USDT',
    baseAsset: 'EGLD',
    priceTickSize: 0.01,
    stepSize: 0.01,
  },
  {
    symbol: 'UNIUSDT',
    quoteAsset: 'USDT',
    baseAsset: 'UNI',
    priceTickSize: 0.001,
    stepSize: 0.01,
  },
  {
    symbol: 'AVAXUSDT',
    quoteAsset: 'USDT',
    baseAsset: 'AVAX',
    priceTickSize: 0.01,
    stepSize: 0.01,
  },
  {
    symbol: 'AAVEUSDT',
    quoteAsset: 'USDT',
    baseAsset: 'AAVE',
    priceTickSize: 0.01,
    stepSize: 0.001,
  },
  {
    symbol: 'NEARUSDT',
    quoteAsset: 'USDT',
    baseAsset: 'NEAR',
    priceTickSize: 0.001,
    stepSize: 0.1,
  },
  {
    symbol: 'FILUSDT',
    quoteAsset: 'USDT',
    baseAsset: 'FIL',
    priceTickSize: 0.001,
    stepSize: 0.01,
  },
  {
    symbol: 'AXSUSDT',
    quoteAsset: 'USDT',
    baseAsset: 'AXS',
    priceTickSize: 0.001,
    stepSize: 0.01,
  },
  {
    symbol: 'GRTUSDT',
    quoteAsset: 'USDT',
    baseAsset: 'GRT',
    priceTickSize: 0.0001,
    stepSize: 1,
  },
  {
    symbol: 'INJUSDT',
    quoteAsset: 'USDT',
    baseAsset: 'INJ',
    priceTickSize: 0.01,
    stepSize: 0.1,
  },
  {
    symbol: 'IMXUSDT',
    quoteAsset: 'USDT',
    baseAsset: 'IMX',
    priceTickSize: 0.0001,
    stepSize: 0.01,
  },
  {
    symbol: 'APTUSDT',
    quoteAsset: 'USDT',
    baseAsset: 'APT',
    priceTickSize: 0.0001,
    stepSize: 0.01,
  },
  {
    symbol: 'RNDRUSDT',
    quoteAsset: 'USDT',
    baseAsset: 'RNDR',
    priceTickSize: 0.001,
    stepSize: 0.01,
  },
  {
    symbol: 'OPUSDT',
    quoteAsset: 'USDT',
    baseAsset: 'OP',
    priceTickSize: 0.001,
    stepSize: 0.01,
  },
  {
    symbol: 'PEPEUSDT',
    quoteAsset: 'USDT',
    baseAsset: 'PEPE',
    priceTickSize: 1e-8,
    stepSize: 1,
  },
  {
    symbol: 'ARUSDT',
    quoteAsset: 'USDT',
    baseAsset: 'AR',
    priceTickSize: 0.001,
    stepSize: 0.01,
  },
  {
    symbol: 'ARBUSDT',
    quoteAsset: 'USDT',
    baseAsset: 'ARB',
    priceTickSize: 0.0001,
    stepSize: 0.1,
  },
  {
    symbol: 'RUNEUSDT',
    quoteAsset: 'USDT',
    baseAsset: 'RUNE',
    priceTickSize: 0.001,
    stepSize: 0.1,
  },
  {
    symbol: 'FETUSDT',
    quoteAsset: 'USDT',
    baseAsset: 'FET',
    priceTickSize: 0.0001,
    stepSize: 1,
  },
  {
    symbol: 'FLOKIUSDT',
    quoteAsset: 'USDT',
    baseAsset: 'FLOKI',
    priceTickSize: 1e-8,
    stepSize: 1,
  },
  {
    symbol: 'MKRUSDT',
    quoteAsset: 'USDT',
    baseAsset: 'MKR',
    priceTickSize: 1,
    stepSize: 0.0001,
  },
  {
    symbol: 'GALAUSDT',
    quoteAsset: 'USDT',
    baseAsset: 'GALA',
    priceTickSize: 0.00001,
    stepSize: 1,
  },
  {
    symbol: 'FLOWUSDT',
    quoteAsset: 'USDT',
    baseAsset: 'FLOW',
    priceTickSize: 0.001,
    stepSize: 0.01,
  },
  {
    symbol: 'LUNCUSDT',
    quoteAsset: 'USDT',
    baseAsset: 'LUNC',
    priceTickSize: 1e-8,
    stepSize: 0.01,
  },
  {
    symbol: 'PYTHUSDT',
    quoteAsset: 'USDT',
    baseAsset: 'PYTH',
    priceTickSize: 0.0001,
    stepSize: 0.1,
  },
  {
    symbol: 'ROSEUSDT',
    quoteAsset: 'USDT',
    baseAsset: 'ROSE',
    priceTickSize: 0.00001,
    stepSize: 0.1,
  },
  {
    symbol: 'RONINUSDT',
    quoteAsset: 'USDT',
    baseAsset: 'RONIN',
    priceTickSize: 0.001,
    stepSize: 0.01,
  },
  {
    symbol: 'NEOUSDT',
    quoteAsset: 'USDT',
    baseAsset: 'NEO',
    priceTickSize: 0.01,
    stepSize: 0.01,
  },
  {
    symbol: 'SNXUSDT',
    quoteAsset: 'USDT',
    baseAsset: 'SNX',
    priceTickSize: 0.001,
    stepSize: 0.1,
  },
  {
    symbol: 'CHZUSDT',
    quoteAsset: 'USDT',
    baseAsset: 'CHZ',
    priceTickSize: 0.00001,
    stepSize: 1,
  },
  {
    symbol: 'MINAUSDT',
    quoteAsset: 'USDT',
    baseAsset: 'MINA',
    priceTickSize: 0.0001,
    stepSize: 0.1,
  },
  {
    symbol: 'AGIXUSDT',
    quoteAsset: 'USDT',
    baseAsset: 'AGIX',
    priceTickSize: 0.00001,
    stepSize: 1,
  },
  {
    symbol: 'BTTCUSDT',
    quoteAsset: 'USDT',
    baseAsset: 'BTTC',
    priceTickSize: 1e-8,
    stepSize: 1,
  },
  {
    symbol: 'OCEANUSDT',
    quoteAsset: 'USDT',
    baseAsset: 'OCEAN',
    priceTickSize: 0.0001,
    stepSize: 1,
  },
  {
    symbol: 'BATUSDT',
    quoteAsset: 'USDT',
    baseAsset: 'BAT',
    priceTickSize: 0.0001,
    stepSize: 1,
  },
  {
    symbol: 'WAVESUSDT',
    quoteAsset: 'USDT',
    baseAsset: 'WAVES',
    priceTickSize: 0.001,
    stepSize: 0.01,
  },
  {
    symbol: 'HOTUSDT',
    quoteAsset: 'USDT',
    baseAsset: 'HOT',
    priceTickSize: 0.000001,
    stepSize: 1,
  },
  {
    symbol: 'QTUMUSDT',
    quoteAsset: 'USDT',
    baseAsset: 'QTUM',
    priceTickSize: 0.001,
    stepSize: 0.1,
  },
  {
    symbol: 'ZRXUSDT',
    quoteAsset: 'USDT',
    baseAsset: 'ZRX',
    priceTickSize: 0.0001,
    stepSize: 1,
  },
  {
    symbol: 'COMPUSDT',
    quoteAsset: 'USDT',
    baseAsset: 'COMP',
    priceTickSize: 0.01,
    stepSize: 0.001,
  },
  {
    symbol: 'LUNAUSDT',
    quoteAsset: 'USDT',
    baseAsset: 'LUNA',
    priceTickSize: 0.0001,
    stepSize: 0.01,
  },
  {
    symbol: 'GMTUSDT',
    quoteAsset: 'USDT',
    baseAsset: 'GMT',
    priceTickSize: 0.0001,
    stepSize: 0.1,
  },
];
