import { Pair } from '.';

export const ALL_PAIRS: Pair[] = [
  {
    symbol: 'ETHBTC',
    quoteAsset: 'BTC',
    baseAsset: 'ETH',
    priceTickSize: 0.000001,
    stepSize: 0.0001,
  },
  {
    symbol: 'LTCBTC',
    quoteAsset: 'BTC',
    baseAsset: 'LTC',
    priceTickSize: 0.000001,
    stepSize: 0.001,
  },
  {
    symbol: 'BNBBTC',
    quoteAsset: 'BTC',
    baseAsset: 'BNB',
    priceTickSize: 0.000001,
    stepSize: 0.001,
  },
  {
    symbol: 'EOSETH',
    quoteAsset: 'ETH',
    baseAsset: 'EOS',
    priceTickSize: 0.000001,
    stepSize: 0.1,
  },
  {
    symbol: 'BNBETH',
    quoteAsset: 'ETH',
    baseAsset: 'BNB',
    priceTickSize: 0.0001,
    stepSize: 0.001,
  },
  {
    symbol: 'BTCUSDT',
    quoteAsset: 'USDT',
    baseAsset: 'BTC',
    priceTickSize: 0.01,
    stepSize: 0.00001,
  },
  {
    symbol: 'ETHUSDT',
    quoteAsset: 'USDT',
    baseAsset: 'ETH',
    priceTickSize: 0.01,
    stepSize: 0.0001,
  },
  {
    symbol: 'LRCBTC',
    quoteAsset: 'BTC',
    baseAsset: 'LRC',
    priceTickSize: 0.00000001,
    stepSize: 1,
  },
  {
    symbol: 'LRCETH',
    quoteAsset: 'ETH',
    baseAsset: 'LRC',
    priceTickSize: 0.00000001,
    stepSize: 1,
  },
  {
    symbol: 'LINKBTC',
    quoteAsset: 'BTC',
    baseAsset: 'LINK',
    priceTickSize: 0.0000001,
    stepSize: 0.01,
  },
  {
    symbol: 'LINKETH',
    quoteAsset: 'ETH',
    baseAsset: 'LINK',
    priceTickSize: 0.000001,
    stepSize: 0.01,
  },
  {
    symbol: 'EOSBTC',
    quoteAsset: 'BTC',
    baseAsset: 'EOS',
    priceTickSize: 0.0000001,
    stepSize: 0.1,
  },
  {
    symbol: 'ZECBTC',
    quoteAsset: 'BTC',
    baseAsset: 'ZEC',
    priceTickSize: 0.000001,
    stepSize: 0.001,
  },
  {
    symbol: 'ZECETH',
    quoteAsset: 'ETH',
    baseAsset: 'ZEC',
    priceTickSize: 0.00001,
    stepSize: 0.001,
  },
  {
    symbol: 'DASHBTC',
    quoteAsset: 'BTC',
    baseAsset: 'DASH',
    priceTickSize: 0.000001,
    stepSize: 0.001,
  },
  {
    symbol: 'DASHETH',
    quoteAsset: 'ETH',
    baseAsset: 'DASH',
    priceTickSize: 0.00001,
    stepSize: 0.001,
  },
  {
    symbol: 'TRXBTC',
    quoteAsset: 'BTC',
    baseAsset: 'TRX',
    priceTickSize: 0.00000001,
    stepSize: 1,
  },
  {
    symbol: 'TRXETH',
    quoteAsset: 'ETH',
    baseAsset: 'TRX',
    priceTickSize: 0.00000001,
    stepSize: 1,
  },
  {
    symbol: 'XRPBTC',
    quoteAsset: 'BTC',
    baseAsset: 'XRP',
    priceTickSize: 0.00000001,
    stepSize: 1,
  },
  {
    symbol: 'XRPETH',
    quoteAsset: 'ETH',
    baseAsset: 'XRP',
    priceTickSize: 0.0000001,
    stepSize: 1,
  },
  {
    symbol: 'ENJBTC',
    quoteAsset: 'BTC',
    baseAsset: 'ENJ',
    priceTickSize: 0.00000001,
    stepSize: 0.1,
  },
  {
    symbol: 'ENJETH',
    quoteAsset: 'ETH',
    baseAsset: 'ENJ',
    priceTickSize: 0.0000001,
    stepSize: 0.1,
  },
  {
    symbol: 'BNBUSDT',
    quoteAsset: 'USDT',
    baseAsset: 'BNB',
    priceTickSize: 0.1,
    stepSize: 0.001,
  },
  {
    symbol: 'XMRBTC',
    quoteAsset: 'BTC',
    baseAsset: 'XMR',
    priceTickSize: 0.000001,
    stepSize: 0.001,
  },
  {
    symbol: 'XMRETH',
    quoteAsset: 'ETH',
    baseAsset: 'XMR',
    priceTickSize: 0.00001,
    stepSize: 0.001,
  },
  {
    symbol: 'BATBTC',
    quoteAsset: 'BTC',
    baseAsset: 'BAT',
    priceTickSize: 0.00000001,
    stepSize: 1,
  },
  {
    symbol: 'BATETH',
    quoteAsset: 'ETH',
    baseAsset: 'BAT',
    priceTickSize: 0.0000001,
    stepSize: 1,
  },
  {
    symbol: 'BATBNB',
    quoteAsset: 'BNB',
    baseAsset: 'BAT',
    priceTickSize: 0.000001,
    stepSize: 1,
  },
  {
    symbol: 'MANABTC',
    quoteAsset: 'BTC',
    baseAsset: 'MANA',
    priceTickSize: 0.00000001,
    stepSize: 1,
  },
  {
    symbol: 'MANAETH',
    quoteAsset: 'ETH',
    baseAsset: 'MANA',
    priceTickSize: 0.0000001,
    stepSize: 1,
  },
  {
    symbol: 'ADABTC',
    quoteAsset: 'BTC',
    baseAsset: 'ADA',
    priceTickSize: 0.00000001,
    stepSize: 0.1,
  },
  {
    symbol: 'ADAETH',
    quoteAsset: 'ETH',
    baseAsset: 'ADA',
    priceTickSize: 0.0000001,
    stepSize: 0.1,
  },
  {
    symbol: 'XLMBTC',
    quoteAsset: 'BTC',
    baseAsset: 'XLM',
    priceTickSize: 0.00000001,
    stepSize: 1,
  },
  {
    symbol: 'XLMETH',
    quoteAsset: 'ETH',
    baseAsset: 'XLM',
    priceTickSize: 0.0000001,
    stepSize: 1,
  },
  {
    symbol: 'XLMBNB',
    quoteAsset: 'BNB',
    baseAsset: 'XLM',
    priceTickSize: 0.0000001,
    stepSize: 1,
  },
  {
    symbol: 'LTCETH',
    quoteAsset: 'ETH',
    baseAsset: 'LTC',
    priceTickSize: 0.00001,
    stepSize: 0.001,
  },
  {
    symbol: 'LTCUSDT',
    quoteAsset: 'USDT',
    baseAsset: 'LTC',
    priceTickSize: 0.01,
    stepSize: 0.001,
  },
  {
    symbol: 'LTCBNB',
    quoteAsset: 'BNB',
    baseAsset: 'LTC',
    priceTickSize: 0.0001,
    stepSize: 0.001,
  },
  {
    symbol: 'WAVESBTC',
    quoteAsset: 'BTC',
    baseAsset: 'WAVES',
    priceTickSize: 0.0000001,
    stepSize: 0.01,
  },
  {
    symbol: 'WAVESETH',
    quoteAsset: 'ETH',
    baseAsset: 'WAVES',
    priceTickSize: 0.000001,
    stepSize: 0.01,
  },
  {
    symbol: 'WAVESBNB',
    quoteAsset: 'BNB',
    baseAsset: 'WAVES',
    priceTickSize: 0.00001,
    stepSize: 0.01,
  },
  {
    symbol: 'ZILBTC',
    quoteAsset: 'BTC',
    baseAsset: 'ZIL',
    priceTickSize: 0.00000001,
    stepSize: 1,
  },
  {
    symbol: 'ZILETH',
    quoteAsset: 'ETH',
    baseAsset: 'ZIL',
    priceTickSize: 0.00000001,
    stepSize: 1,
  },
  {
    symbol: 'ZILBNB',
    quoteAsset: 'BNB',
    baseAsset: 'ZIL',
    priceTickSize: 0.0000001,
    stepSize: 1,
  },
  {
    symbol: 'ADAUSDT',
    quoteAsset: 'USDT',
    baseAsset: 'ADA',
    priceTickSize: 0.0001,
    stepSize: 0.1,
  },
  {
    symbol: 'ADABNB',
    quoteAsset: 'BNB',
    baseAsset: 'ADA',
    priceTickSize: 0.000001,
    stepSize: 0.1,
  },
  {
    symbol: 'XRPUSDT',
    quoteAsset: 'USDT',
    baseAsset: 'XRP',
    priceTickSize: 0.0001,
    stepSize: 1,
  },
  {
    symbol: 'EOSUSDT',
    quoteAsset: 'USDT',
    baseAsset: 'EOS',
    priceTickSize: 0.001,
    stepSize: 0.1,
  },
  {
    symbol: 'EOSBNB',
    quoteAsset: 'BNB',
    baseAsset: 'EOS',
    priceTickSize: 0.00001,
    stepSize: 0.1,
  },
  {
    symbol: 'THETABTC',
    quoteAsset: 'BTC',
    baseAsset: 'THETA',
    priceTickSize: 0.0000001,
    stepSize: 0.1,
  },
  {
    symbol: 'THETAETH',
    quoteAsset: 'ETH',
    baseAsset: 'THETA',
    priceTickSize: 0.000001,
    stepSize: 0.1,
  },
  {
    symbol: 'THETABNB',
    quoteAsset: 'BNB',
    baseAsset: 'THETA',
    priceTickSize: 0.00001,
    stepSize: 0.1,
  },
  {
    symbol: 'XRPBNB',
    quoteAsset: 'BNB',
    baseAsset: 'XRP',
    priceTickSize: 0.000001,
    stepSize: 1,
  },
  {
    symbol: 'XLMUSDT',
    quoteAsset: 'USDT',
    baseAsset: 'XLM',
    priceTickSize: 0.0001,
    stepSize: 1,
  },
  {
    symbol: 'ENJBNB',
    quoteAsset: 'BNB',
    baseAsset: 'ENJ',
    priceTickSize: 0.000001,
    stepSize: 0.1,
  },
  {
    symbol: 'TRXBNB',
    quoteAsset: 'BNB',
    baseAsset: 'TRX',
    priceTickSize: 0.0000001,
    stepSize: 1,
  },
  {
    symbol: 'TRXUSDT',
    quoteAsset: 'USDT',
    baseAsset: 'TRX',
    priceTickSize: 0.00001,
    stepSize: 0.1,
  },
  {
    symbol: 'VETBTC',
    quoteAsset: 'BTC',
    baseAsset: 'VET',
    priceTickSize: 0.00000001,
    stepSize: 1,
  },
  {
    symbol: 'VETETH',
    quoteAsset: 'ETH',
    baseAsset: 'VET',
    priceTickSize: 0.00000001,
    stepSize: 1,
  },
  {
    symbol: 'VETUSDT',
    quoteAsset: 'USDT',
    baseAsset: 'VET',
    priceTickSize: 0.00001,
    stepSize: 0.1,
  },
  {
    symbol: 'VETBNB',
    quoteAsset: 'BNB',
    baseAsset: 'VET',
    priceTickSize: 0.0000001,
    stepSize: 1,
  },
  {
    symbol: 'LINKUSDT',
    quoteAsset: 'USDT',
    baseAsset: 'LINK',
    priceTickSize: 0.01,
    stepSize: 0.01,
  },
  {
    symbol: 'WAVESUSDT',
    quoteAsset: 'USDT',
    baseAsset: 'WAVES',
    priceTickSize: 0.01,
    stepSize: 0.01,
  },
  {
    symbol: 'ZILUSDT',
    quoteAsset: 'USDT',
    baseAsset: 'ZIL',
    priceTickSize: 0.00001,
    stepSize: 0.1,
  },
  {
    symbol: 'BATUSDT',
    quoteAsset: 'USDT',
    baseAsset: 'BAT',
    priceTickSize: 0.0001,
    stepSize: 1,
  },
  {
    symbol: 'XMRBNB',
    quoteAsset: 'BNB',
    baseAsset: 'XMR',
    priceTickSize: 0.0001,
    stepSize: 0.001,
  },
  {
    symbol: 'XMRUSDT',
    quoteAsset: 'USDT',
    baseAsset: 'XMR',
    priceTickSize: 0.1,
    stepSize: 0.001,
  },
  {
    symbol: 'ZECBNB',
    quoteAsset: 'BNB',
    baseAsset: 'ZEC',
    priceTickSize: 0.0001,
    stepSize: 0.001,
  },
  {
    symbol: 'ZECUSDT',
    quoteAsset: 'USDT',
    baseAsset: 'ZEC',
    priceTickSize: 0.1,
    stepSize: 0.001,
  },
  {
    symbol: 'DASHBNB',
    quoteAsset: 'BNB',
    baseAsset: 'DASH',
    priceTickSize: 0.0001,
    stepSize: 0.001,
  },
  {
    symbol: 'DASHUSDT',
    quoteAsset: 'USDT',
    baseAsset: 'DASH',
    priceTickSize: 0.1,
    stepSize: 0.001,
  },
  {
    symbol: 'THETAUSDT',
    quoteAsset: 'USDT',
    baseAsset: 'THETA',
    priceTickSize: 0.001,
    stepSize: 0.1,
  },
  {
    symbol: 'ENJUSDT',
    quoteAsset: 'USDT',
    baseAsset: 'ENJ',
    priceTickSize: 0.001,
    stepSize: 0.1,
  },
  {
    symbol: 'MATICBNB',
    quoteAsset: 'BNB',
    baseAsset: 'MATIC',
    priceTickSize: 0.000001,
    stepSize: 0.1,
  },
  {
    symbol: 'MATICBTC',
    quoteAsset: 'BTC',
    baseAsset: 'MATIC',
    priceTickSize: 0.00000001,
    stepSize: 0.1,
  },
  {
    symbol: 'MATICUSDT',
    quoteAsset: 'USDT',
    baseAsset: 'MATIC',
    priceTickSize: 0.0001,
    stepSize: 0.1,
  },
  {
    symbol: 'ATOMBNB',
    quoteAsset: 'BNB',
    baseAsset: 'ATOM',
    priceTickSize: 0.00001,
    stepSize: 0.01,
  },
  {
    symbol: 'ATOMBTC',
    quoteAsset: 'BTC',
    baseAsset: 'ATOM',
    priceTickSize: 0.0000001,
    stepSize: 0.01,
  },
  {
    symbol: 'ATOMUSDT',
    quoteAsset: 'USDT',
    baseAsset: 'ATOM',
    priceTickSize: 0.01,
    stepSize: 0.01,
  },
  {
    symbol: 'FTMBNB',
    quoteAsset: 'BNB',
    baseAsset: 'FTM',
    priceTickSize: 0.0000001,
    stepSize: 1,
  },
  {
    symbol: 'FTMBTC',
    quoteAsset: 'BTC',
    baseAsset: 'FTM',
    priceTickSize: 0.00000001,
    stepSize: 1,
  },
  {
    symbol: 'FTMUSDT',
    quoteAsset: 'USDT',
    baseAsset: 'FTM',
    priceTickSize: 0.0001,
    stepSize: 1,
  },
  {
    symbol: 'ALGOBNB',
    quoteAsset: 'BNB',
    baseAsset: 'ALGO',
    priceTickSize: 0.000001,
    stepSize: 1,
  },
  {
    symbol: 'ALGOBTC',
    quoteAsset: 'BTC',
    baseAsset: 'ALGO',
    priceTickSize: 0.00000001,
    stepSize: 1,
  },
  {
    symbol: 'ALGOUSDT',
    quoteAsset: 'USDT',
    baseAsset: 'ALGO',
    priceTickSize: 0.0001,
    stepSize: 1,
  },
  {
    symbol: 'DOGEBNB',
    quoteAsset: 'BNB',
    baseAsset: 'DOGE',
    priceTickSize: 0.00000001,
    stepSize: 1,
  },
  {
    symbol: 'DOGEBTC',
    quoteAsset: 'BTC',
    baseAsset: 'DOGE',
    priceTickSize: 0.00000001,
    stepSize: 1,
  },
  {
    symbol: 'DOGEUSDT',
    quoteAsset: 'USDT',
    baseAsset: 'DOGE',
    priceTickSize: 0.00001,
    stepSize: 1,
  },
  {
    symbol: 'XTZBNB',
    quoteAsset: 'BNB',
    baseAsset: 'XTZ',
    priceTickSize: 0.000001,
    stepSize: 0.1,
  },
  {
    symbol: 'XTZBTC',
    quoteAsset: 'BTC',
    baseAsset: 'XTZ',
    priceTickSize: 0.00000001,
    stepSize: 0.1,
  },
  {
    symbol: 'XTZUSDT',
    quoteAsset: 'USDT',
    baseAsset: 'XTZ',
    priceTickSize: 0.001,
    stepSize: 0.1,
  },
  {
    symbol: 'HBARBNB',
    quoteAsset: 'BNB',
    baseAsset: 'HBAR',
    priceTickSize: 0.0000001,
    stepSize: 1,
  },
  {
    symbol: 'HBARBTC',
    quoteAsset: 'BTC',
    baseAsset: 'HBAR',
    priceTickSize: 0.00000001,
    stepSize: 1,
  },
  {
    symbol: 'HBARUSDT',
    quoteAsset: 'USDT',
    baseAsset: 'HBAR',
    priceTickSize: 0.0001,
    stepSize: 1,
  },
  {
    symbol: 'STXBNB',
    quoteAsset: 'BNB',
    baseAsset: 'STX',
    priceTickSize: 0.000001,
    stepSize: 0.1,
  },
  {
    symbol: 'STXBTC',
    quoteAsset: 'BTC',
    baseAsset: 'STX',
    priceTickSize: 0.00000001,
    stepSize: 0.1,
  },
  {
    symbol: 'STXUSDT',
    quoteAsset: 'USDT',
    baseAsset: 'STX',
    priceTickSize: 0.001,
    stepSize: 0.1,
  },
  {
    symbol: 'BCHBNB',
    quoteAsset: 'BNB',
    baseAsset: 'BCH',
    priceTickSize: 0.001,
    stepSize: 0.001,
  },
  {
    symbol: 'BCHBTC',
    quoteAsset: 'BTC',
    baseAsset: 'BCH',
    priceTickSize: 0.00001,
    stepSize: 0.001,
  },
  {
    symbol: 'BCHUSDT',
    quoteAsset: 'USDT',
    baseAsset: 'BCH',
    priceTickSize: 0.1,
    stepSize: 0.001,
  },
  {
    symbol: 'FTTBNB',
    quoteAsset: 'BNB',
    baseAsset: 'FTT',
    priceTickSize: 0.0001,
    stepSize: 0.01,
  },
  {
    symbol: 'FTTBTC',
    quoteAsset: 'BTC',
    baseAsset: 'FTT',
    priceTickSize: 0.0000001,
    stepSize: 0.01,
  },
  {
    symbol: 'FTTUSDT',
    quoteAsset: 'USDT',
    baseAsset: 'FTT',
    priceTickSize: 0.01,
    stepSize: 0.01,
  },
  {
    symbol: 'SOLBNB',
    quoteAsset: 'BNB',
    baseAsset: 'SOL',
    priceTickSize: 0.0001,
    stepSize: 0.01,
  },
  {
    symbol: 'SOLBTC',
    quoteAsset: 'BTC',
    baseAsset: 'SOL',
    priceTickSize: 0.0000001,
    stepSize: 0.01,
  },
  {
    symbol: 'SOLUSDT',
    quoteAsset: 'USDT',
    baseAsset: 'SOL',
    priceTickSize: 0.01,
    stepSize: 0.01,
  },
  {
    symbol: 'LRCUSDT',
    quoteAsset: 'USDT',
    baseAsset: 'LRC',
    priceTickSize: 0.0001,
    stepSize: 1,
  },
  {
    symbol: 'MANAUSDT',
    quoteAsset: 'USDT',
    baseAsset: 'MANA',
    priceTickSize: 0.0001,
    stepSize: 1,
  },
  {
    symbol: 'CRVBNB',
    quoteAsset: 'BNB',
    baseAsset: 'CRV',
    priceTickSize: 0.000001,
    stepSize: 0.1,
  },
  {
    symbol: 'CRVBTC',
    quoteAsset: 'BTC',
    baseAsset: 'CRV',
    priceTickSize: 0.00000001,
    stepSize: 0.1,
  },
  {
    symbol: 'CRVUSDT',
    quoteAsset: 'USDT',
    baseAsset: 'CRV',
    priceTickSize: 0.001,
    stepSize: 0.1,
  },
  {
    symbol: 'SANDBNB',
    quoteAsset: 'BNB',
    baseAsset: 'SAND',
    priceTickSize: 0.000001,
    stepSize: 1,
  },
  {
    symbol: 'SANDBTC',
    quoteAsset: 'BTC',
    baseAsset: 'SAND',
    priceTickSize: 0.00000001,
    stepSize: 1,
  },
  {
    symbol: 'SANDUSDT',
    quoteAsset: 'USDT',
    baseAsset: 'SAND',
    priceTickSize: 0.0001,
    stepSize: 1,
  },
  {
    symbol: 'DOTBNB',
    quoteAsset: 'BNB',
    baseAsset: 'DOT',
    priceTickSize: 0.00001,
    stepSize: 0.01,
  },
  {
    symbol: 'DOTBTC',
    quoteAsset: 'BTC',
    baseAsset: 'DOT',
    priceTickSize: 0.0000001,
    stepSize: 0.01,
  },
  {
    symbol: 'DOTUSDT',
    quoteAsset: 'USDT',
    baseAsset: 'DOT',
    priceTickSize: 0.01,
    stepSize: 0.01,
  },
  {
    symbol: 'EGLDBNB',
    quoteAsset: 'BNB',
    baseAsset: 'EGLD',
    priceTickSize: 0.0001,
    stepSize: 0.01,
  },
  {
    symbol: 'EGLDBTC',
    quoteAsset: 'BTC',
    baseAsset: 'EGLD',
    priceTickSize: 0.000001,
    stepSize: 0.01,
  },
  {
    symbol: 'EGLDUSDT',
    quoteAsset: 'USDT',
    baseAsset: 'EGLD',
    priceTickSize: 0.01,
    stepSize: 0.01,
  },
  {
    symbol: 'UNIBNB',
    quoteAsset: 'BNB',
    baseAsset: 'UNI',
    priceTickSize: 0.00001,
    stepSize: 0.01,
  },
  {
    symbol: 'UNIBTC',
    quoteAsset: 'BTC',
    baseAsset: 'UNI',
    priceTickSize: 0.0000001,
    stepSize: 0.01,
  },
  {
    symbol: 'UNIUSDT',
    quoteAsset: 'USDT',
    baseAsset: 'UNI',
    priceTickSize: 0.01,
    stepSize: 0.01,
  },
  {
    symbol: 'AVAXBNB',
    quoteAsset: 'BNB',
    baseAsset: 'AVAX',
    priceTickSize: 0.00001,
    stepSize: 0.01,
  },
  {
    symbol: 'AVAXBTC',
    quoteAsset: 'BTC',
    baseAsset: 'AVAX',
    priceTickSize: 0.0000001,
    stepSize: 0.01,
  },
  {
    symbol: 'AVAXUSDT',
    quoteAsset: 'USDT',
    baseAsset: 'AVAX',
    priceTickSize: 0.01,
    stepSize: 0.01,
  },
  {
    symbol: 'HNTBTC',
    quoteAsset: 'BTC',
    baseAsset: 'HNT',
    priceTickSize: 0.0000001,
    stepSize: 0.01,
  },
  {
    symbol: 'HNTUSDT',
    quoteAsset: 'USDT',
    baseAsset: 'HNT',
    priceTickSize: 0.01,
    stepSize: 0.01,
  },
  {
    symbol: 'AAVEBNB',
    quoteAsset: 'BNB',
    baseAsset: 'AAVE',
    priceTickSize: 0.0001,
    stepSize: 0.001,
  },
  {
    symbol: 'AAVEBTC',
    quoteAsset: 'BTC',
    baseAsset: 'AAVE',
    priceTickSize: 0.000001,
    stepSize: 0.001,
  },
  {
    symbol: 'AAVEETH',
    quoteAsset: 'ETH',
    baseAsset: 'AAVE',
    priceTickSize: 0.0001,
    stepSize: 0.001,
  },
  {
    symbol: 'AAVEUSDT',
    quoteAsset: 'USDT',
    baseAsset: 'AAVE',
    priceTickSize: 0.1,
    stepSize: 0.001,
  },
  {
    symbol: 'NEARBNB',
    quoteAsset: 'BNB',
    baseAsset: 'NEAR',
    priceTickSize: 0.000001,
    stepSize: 0.1,
  },
  {
    symbol: 'NEARBTC',
    quoteAsset: 'BTC',
    baseAsset: 'NEAR',
    priceTickSize: 0.00000001,
    stepSize: 0.1,
  },
  {
    symbol: 'NEARUSDT',
    quoteAsset: 'USDT',
    baseAsset: 'NEAR',
    priceTickSize: 0.001,
    stepSize: 0.1,
  },
  {
    symbol: 'FILBNB',
    quoteAsset: 'BNB',
    baseAsset: 'FIL',
    priceTickSize: 0.0001,
    stepSize: 0.01,
  },
  {
    symbol: 'FILBTC',
    quoteAsset: 'BTC',
    baseAsset: 'FIL',
    priceTickSize: 0.000001,
    stepSize: 0.01,
  },
  {
    symbol: 'FILUSDT',
    quoteAsset: 'USDT',
    baseAsset: 'FIL',
    priceTickSize: 0.01,
    stepSize: 0.01,
  },
  {
    symbol: 'AXSBNB',
    quoteAsset: 'BNB',
    baseAsset: 'AXS',
    priceTickSize: 0.0001,
    stepSize: 0.01,
  },
  {
    symbol: 'AXSBTC',
    quoteAsset: 'BTC',
    baseAsset: 'AXS',
    priceTickSize: 0.000001,
    stepSize: 0.01,
  },
  {
    symbol: 'AXSUSDT',
    quoteAsset: 'USDT',
    baseAsset: 'AXS',
    priceTickSize: 0.01,
    stepSize: 0.01,
  },
  {
    symbol: 'GRTBTC',
    quoteAsset: 'BTC',
    baseAsset: 'GRT',
    priceTickSize: 0.00000001,
    stepSize: 1,
  },
  {
    symbol: 'GRTETH',
    quoteAsset: 'ETH',
    baseAsset: 'GRT',
    priceTickSize: 0.0000001,
    stepSize: 1,
  },
  {
    symbol: 'GRTUSDT',
    quoteAsset: 'USDT',
    baseAsset: 'GRT',
    priceTickSize: 0.0001,
    stepSize: 1,
  },
  {
    symbol: '1INCHBTC',
    quoteAsset: 'BTC',
    baseAsset: '1INCH',
    priceTickSize: 0.00000001,
    stepSize: 0.1,
  },
  {
    symbol: '1INCHUSDT',
    quoteAsset: 'USDT',
    baseAsset: '1INCH',
    priceTickSize: 0.001,
    stepSize: 0.1,
  },
  {
    symbol: 'AXSETH',
    quoteAsset: 'ETH',
    baseAsset: 'AXS',
    priceTickSize: 0.00001,
    stepSize: 0.001,
  },
  {
    symbol: 'FTMETH',
    quoteAsset: 'ETH',
    baseAsset: 'FTM',
    priceTickSize: 0.0000001,
    stepSize: 0.1,
  },
  {
    symbol: 'SOLETH',
    quoteAsset: 'ETH',
    baseAsset: 'SOL',
    priceTickSize: 0.00001,
    stepSize: 0.001,
  },
  {
    symbol: 'SANDETH',
    quoteAsset: 'ETH',
    baseAsset: 'SAND',
    priceTickSize: 0.0000001,
    stepSize: 0.1,
  },
  {
    symbol: 'DOTETH',
    quoteAsset: 'ETH',
    baseAsset: 'DOT',
    priceTickSize: 0.000001,
    stepSize: 0.01,
  },
  {
    symbol: 'MATICETH',
    quoteAsset: 'ETH',
    baseAsset: 'MATIC',
    priceTickSize: 0.0000001,
    stepSize: 0.1,
  },
  {
    symbol: 'AVAXETH',
    quoteAsset: 'ETH',
    baseAsset: 'AVAX',
    priceTickSize: 0.00001,
    stepSize: 0.01,
  },
  {
    symbol: 'AMPBTC',
    quoteAsset: 'BTC',
    baseAsset: 'AMP',
    priceTickSize: 0.00000001,
    stepSize: 1,
  },
  {
    symbol: 'AMPBNB',
    quoteAsset: 'BNB',
    baseAsset: 'AMP',
    priceTickSize: 0.00000001,
    stepSize: 1,
  },
  {
    symbol: 'AMPUSDT',
    quoteAsset: 'USDT',
    baseAsset: 'AMP',
    priceTickSize: 0.00001,
    stepSize: 1,
  },
  {
    symbol: 'MANABNB',
    quoteAsset: 'BNB',
    baseAsset: 'MANA',
    priceTickSize: 0.000001,
    stepSize: 0.01,
  },
  {
    symbol: 'LINKBNB',
    quoteAsset: 'BNB',
    baseAsset: 'LINK',
    priceTickSize: 0.00001,
    stepSize: 0.001,
  },
  {
    symbol: 'ATOMETH',
    quoteAsset: 'ETH',
    baseAsset: 'ATOM',
    priceTickSize: 0.00001,
    stepSize: 0.001,
  },
  {
    symbol: 'EGLDETH',
    quoteAsset: 'ETH',
    baseAsset: 'EGLD',
    priceTickSize: 0.00001,
    stepSize: 0.0001,
  },
  {
    symbol: 'NEARETH',
    quoteAsset: 'ETH',
    baseAsset: 'NEAR',
    priceTickSize: 0.000001,
    stepSize: 0.001,
  },
  {
    symbol: 'LRCBNB',
    quoteAsset: 'BNB',
    baseAsset: 'LRC',
    priceTickSize: 0.000001,
    stepSize: 0.01,
  },
  {
    symbol: 'UNIETH',
    quoteAsset: 'ETH',
    baseAsset: 'UNI',
    priceTickSize: 0.000001,
    stepSize: 0.001,
  },
  {
    symbol: 'XTZETH',
    quoteAsset: 'ETH',
    baseAsset: 'XTZ',
    priceTickSize: 0.000001,
    stepSize: 0.01,
  },
  {
    symbol: 'CRVETH',
    quoteAsset: 'ETH',
    baseAsset: 'CRV',
    priceTickSize: 0.000001,
    stepSize: 0.01,
  },
  {
    symbol: 'FTTETH',
    quoteAsset: 'ETH',
    baseAsset: 'FTT',
    priceTickSize: 0.00001,
    stepSize: 0.001,
  },
  {
    symbol: 'ALGOETH',
    quoteAsset: 'ETH',
    baseAsset: 'ALGO',
    priceTickSize: 0.0000001,
    stepSize: 0.1,
  },
];
