import { Pair } from '.';

export const ALL_PAIRS: Pair[] = [
  {
    symbol: 'BTCUSDT',
    quoteAsset: 'USDT',
    baseAsset: 'BTC',
    priceTickSize: 0.01,
    stepSize: 0.00001,
  },
  {
    symbol: 'ETHUSDT',
    quoteAsset: 'USDT',
    baseAsset: 'ETH',
    priceTickSize: 0.01,
    stepSize: 0.0001,
  },
  {
    symbol: 'LTCUSDT',
    quoteAsset: 'USDT',
    baseAsset: 'LTC',
    priceTickSize: 0.01,
    stepSize: 0.001,
  },
  {
    symbol: 'ADAUSDT',
    quoteAsset: 'USDT',
    baseAsset: 'ADA',
    priceTickSize: 0.0001,
    stepSize: 0.1,
  },
  {
    symbol: 'XRPUSDT',
    quoteAsset: 'USDT',
    baseAsset: 'XRP',
    priceTickSize: 0.0001,
    stepSize: 1,
  },
  {
    symbol: 'XLMUSDT',
    quoteAsset: 'USDT',
    baseAsset: 'XLM',
    priceTickSize: 0.0001,
    stepSize: 1,
  },
  {
    symbol: 'TRXUSDT',
    quoteAsset: 'USDT',
    baseAsset: 'TRX',
    priceTickSize: 0.0001,
    stepSize: 0.1,
  },
  {
    symbol: 'VETUSDT',
    quoteAsset: 'USDT',
    baseAsset: 'VET',
    priceTickSize: 0.00001,
    stepSize: 0.1,
  },
  {
    symbol: 'LINKUSDT',
    quoteAsset: 'USDT',
    baseAsset: 'LINK',
    priceTickSize: 0.01,
    stepSize: 0.01,
  },
  {
    symbol: 'ATOMUSDT',
    quoteAsset: 'USDT',
    baseAsset: 'ATOM',
    priceTickSize: 0.001,
    stepSize: 0.01,
  },
  {
    symbol: 'DOGEUSDT',
    quoteAsset: 'USDT',
    baseAsset: 'DOGE',
    priceTickSize: 0.00001,
    stepSize: 1,
  },
  {
    symbol: 'BCHUSDT',
    quoteAsset: 'USDT',
    baseAsset: 'BCH',
    priceTickSize: 0.1,
    stepSize: 0.001,
  },
  {
    symbol: 'SOLUSDT',
    quoteAsset: 'USDT',
    baseAsset: 'SOL',
    priceTickSize: 0.01,
    stepSize: 0.001,
  },
  {
    symbol: 'DOTUSDT',
    quoteAsset: 'USDT',
    baseAsset: 'DOT',
    priceTickSize: 0.001,
    stepSize: 0.01,
  },
  {
    symbol: 'UNIUSDT',
    quoteAsset: 'USDT',
    baseAsset: 'UNI',
    priceTickSize: 0.001,
    stepSize: 0.01,
  },
  {
    symbol: 'AVAXUSDT',
    quoteAsset: 'USDT',
    baseAsset: 'AVAX',
    priceTickSize: 0.01,
    stepSize: 0.01,
  },
];
